# Generated by Django 2.1.7 on 2019-04-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190420_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='created_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='prefecture',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
